language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

notifications:
  webhooks: https://hooks.pubu.im/services/m8g89bmggle9iq

install:
  - "npm install"

script:
  - "node_modules/gulp/bin/gulp.js"